### ISSUE TITLE
Dependency jars missings

### ISSUE THREAD

**Issue by bandops** [sematext/solr-autocomplete#1]
Hi,

  I'm trying to build the Autocomplete codebase from source. The "mvn clean package" is failing due to missing dependency jars.

[ERROR] Failed to execute goal on project st-AutoComplete: Could not resolve dependencies for project com.sematext.autocomplete:st-AutoComplete:jar:1.6.6.0.1-SNAPSHOT: The following artifacts could not be resolved: com.sematext.solr:st-ReSearcher-core:jar:1.12.6.0.1-SNAPSHOT, com.sematext.querysegmenter:st-QuerySegmenter-core:jar:1.3.6.0.1-SNAPSHOT: Could not find artifact com.sematext.solr:st-ReSearcher-core:jar:1.12.6.0.1-SNAPSHOT -> [Help 1]

Can you please let me know how to include the two jar files?

-Thanks

**Comment by nmtien** [comment]
I fixed it, thanks.

**Comment by bandops** [comment]
Thanks a lot.

**Comment by mmenezes** [comment]
I am unable to build on CentOS Linux release 7.5.1804 (Core).  Java version 
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)

I get the following error
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:42 min
[INFO] Finished at: 2019-12-04T14:03:37+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project st-AutoComplete: Could not resolve dependencies for project com.sematext.autocomplete:st-AutoComplete:jar:1.6.7.1.1-SNAPSHOT: The following artifacts could not be resolved: org.restlet.jee:org.restlet:jar:2.3.0, org.restlet.jee:org.restlet.ext.servlet:jar:2.3.0: Could not transfer artifact org.restlet.jee:org.restlet:jar:2.3.0 from/to maven-restlet (http://maven.restlet.org): Failed to transfer file http://maven.restlet.org/org/restlet/jee/org.restlet/2.3.0/org.restlet-2.3.0.jar with status code 503 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by wiistriker** [comment]
Open pom.xml file and add new repository in repositores section

  ```
  <repository>
      <id>maven-restlet</id>
      <name>Public online Restlet repository</name>
      <url>https://maven.restlet.com</url>
    </repository>
```
