### ISSUE TITLE
There are no results returned if the last input word is of a single character

### ISSUE THREAD

**Issue by siddharths1** [sematext/solr-autocomplete#6]
When the request is for a single character word, or there is a single character in the last word, no results are returned.

Eg. : If 'solr autocomplete' is a document in the index, and we search for 's', then no results are returned. But 'so', 'sol', etc, all return the documents successfully. Again, when we submit a query with just one character as the last word, no results are returned. 'solr a' produced no results. But, after providing more characters in this last word, the document was returned in the result.

Any help to resolve this issue would be appreciated.

**Comment by bsmid** [comment]
AC has few different modes of work and in some of them it is by design that at least 2 characters are needed to produce a suggestion. Can you show full query URL you are using (so handler and all params are visible)?

**Comment by siddharths1** [comment]
Single character word in query, URL -
http://localhost:7075/solr/ac/select?ac_spellcheck=true&q=s&qt=dismax_ac

Response:
```{
  "responseHeader":{
    "status":0,
    "QTime":1,
    "params":{
      "ac_spellcheck":"true",
      "q":"s",
      "qt":"dismax_ac"}},
  "response":{"numFound":0,"start":0,"docs":[]
  }}
```

Two character word in query, URL -
http://localhost:7075/solr/ac/select?ac_spellcheck=true&q=so&qt=dismax_ac

Response:
```{
  "responseHeader":{
    "status":0,
    "QTime":0,
    "params":{
      "ac_spellcheck":"true",
      "q":"so",
      "qt":"dismax_ac"}},
  "response":{"numFound":1,"start":0,"docs":[
      {
        "phrase":"solr autocomplete",
        "_version_":1608783098589216768}]
  }}
```

**Comment by bsmid** [comment]
Yeah, in this case (when using request parameter `ac_spellcheck=true`) search depends on `phraseSpellchecking` schema field. This field is defined as:

`<field name="phraseSpellchecking" type="prefixTokTypeNgram" indexed="true" stored="false"/>`

where type `prefixTokTypeNgram` is:

``` xml
<fieldType name="prefixTokTypeNgram" class="solr.TextField" positionIncrementGap="1">
    <analyzer>
      <tokenizer class="solr.KeywordTokenizerFactory"/>
      <filter class="solr.LowerCaseFilterFactory"/>
      <filter class="solr.NGramFilterFactory" maxGramSize="3" minGramSize="2"/>
      <filter class="org.apache.lucene.analysis.position.PositionFilterFactory"/>
    </analyzer>
  </fieldType>
```

Here lies your problem - `minGramSize=2`. To "fix" it, you could just set `minGramSize=1` (note that you would have to reindex your data), in that case single-letter searches will also produce results, though you may not be very satisfied with their quality.

**Comment by siddharths1** [comment]
Worked! Thanks
